//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerid { get; set; }
        public string customername { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
    
        public virtual City City1 { get; set; }
    }
}
